# conversations.py
# 30 kịch bản hội thoại Kessoku Band
# Mỗi kịch bản 20 câu (tuple) - Tổng cộng 600 câu
# Có dấu, không emoji, không dấu ba chấm

SCENARIOS = [
    # KỊCH BẢN 1: Chuẩn bị cho buổi tập
    [
        ("Nijika", "Mọi người ơi hôm nay chúng ta tập bài mới nhé"),
        ("Kita", "Em rất mong cho hôm nay luôn ạ chắc sẽ vui lắm"),
        ("Ryo", "Tôi không mang tiền theo ai bao trưa nay đi"),
        ("Kikuri", "Ối hôm qua tôi uống say quá giờ vẫn còn mệt"),
        ("Hitori", "Em chuẩn bị guitar rồi ạ dây đàn đủ cả ạ"),
        ("PA-san", "Phòng tập đã được dọn dẹp có thể bắt đầu được rồi"),
        ("Seika", "Nhớ tắt âm thanh trước khi chơi đừng để gây ồn"),
        ("Nijika", "Hitori em đánh leading cho bài này nhé"),
        ("Hitori", "Dạ em sẽ cố gắng ạ nhưng em sợ làm sai ạ"),
        ("Kita", "Senpai đánh giỏi lắm em tin tưởng vào senpai"),
        ("Ryo", "Tôi thật sự không muốn chơi bài này nó nhạt"),
        ("Kikuri", "Thế thì chúng ta chơi bài thật nhanh đi cho nó vui"),
        ("PA-san", "Bài tập là bài bắt buộc không thể bỏ qua"),
        ("Seika", "Đừng cãi nhau nữa tập đi rồi tính sau"),
        ("Nijika", "Bắt đầu đếm 1 2 3 4 các em đánh lên nào"),
        ("Hitori", "A a a em lo mất rồi cho em bắt lại ạ"),
        ("Kita", "Senpai đừng lo em đánh theo senpai mà"),
        ("Ryo", "Tôi thấy Hitori chơi tốt mà cái gì mà lo"),
        ("Kikuri", "Ui trời bài này hay đấy say rượu nghe càng hay"),
        ("Seika", "Tập trung vào đừng để mất tập trung như vậy"),
    ],

    # KỊCH BẢN 2: Giờ giải lao
    [
        ("Nijika", "Nghỉ giải lao 15 phút nhé mọi người"),
        ("Kita", "Em mua nước cho mọi người nhé em đi đây"),
        ("Ryo", "Mua cho tôi trà sữa tôi sẽ trả tiền sau"),
        ("Kikuri", "Tôi muốn bia có được không không bia không vui"),
        ("Hitori", "Em chỉ cần nước lọc thôi ạ cảm ơn ạ"),
        ("PA-san", "Đừng uống bia trong giờ tập mất tập trung"),
        ("Seika", "Kikuri em lại say rồi hôm nay mấy giờ mà"),
        ("Kikuri", "Em không say ạ em mới uống có 2 chai thôi ạ"),
        ("Nijika", "2 chai mà còn bảo không say trời ơi"),
        ("Kita", "Chị Kikuri vui tính thật nhưng em nghĩ nên uống nước"),
        ("Ryo", "Tôi thật sự cần một ly trà sữa để sống"),
        ("Hitori", "Em thấy mọi người vui vẻ thật ạ"),
        ("Seika", "Nijika em quản lý tốt cố gắng phát huy nhé"),
        ("PA-san", "Hôm nay tiến bộ hơn hôm qua giữ vậy là tốt"),
        ("Kikuri", "Hay quá vậy mà không có bia thì thật là phung phí"),
        ("Nijika", "Tập xong rồi uống cũng được kiềm chế đi"),
        ("Kita", "Em về đây nước đầy đủ ạ"),
        ("Ryo", "Cảm ơn Kita lần sau tôi sẽ trả tiền"),
        ("Hitori", "Cảm ơn chị Kita ạ em uống một hơi hết luôn ạ"),
        ("Seika", "Nghỉ tiếp 5 phút nữa rồi tập tiếp cố gắng lên"),
    ],

    # KỊCH BẢN 3: Sự cố dây đàn bị đứt
    [
        ("Hitori", "A a a em xin lỗi ạ dây đàn em bị đứt rồi ạ"),
        ("Nijika", "Sao lại đứt được em đánh mạnh quá hay sao"),
        ("Kita", "Để em xem nào ối thật rồi đứt thật rồi kìa"),
        ("Ryo", "Tôi có dây đàn dư nhưng phải trả tiền"),
        ("Kikuri", "Ui trời xui quá vậy hôm qua tôi cũng bị đứt"),
        ("PA-san", "Có dây đàn dự trữ không hay cần đi mua"),
        ("Seika", "Trong kho của quán có vài bộ để tôi lấy cho"),
        ("Hitori", "Em xin lỗi ạ em sẽ cẩn thận hơn ạ"),
        ("Nijika", "Không sao tai nạn nghề nhạc là chuyện thường"),
        ("Kita", "Senpai đừng lo em thấy senpai đánh nhiệt tình mà"),
        ("Ryo", "Nhưng mà tôi vẫn nghĩ nên trả tiền cho tôi"),
        ("Kikuri", "Để tôi ứng trước cho nhưng nhớ trả gấp đôi nhé"),
        ("Hitori", "Em sẽ trả ạ để em lấy tiền tiết kiệm ạ"),
        ("Seika", "Thôi khỏi quán tài trợ cho xem như phí thuê"),
        ("PA-san", "Những lần sau hãy kiểm tra dây đàn trước khi chơi"),
        ("Nijika", "Đừng vậy Hitori có thể mượn đàn của em tạm"),
        ("Kita", "Em cũng có thể cho senpai mượn đàn của em ạ"),
        ("Ryo", "Mọi người tốt quá còn tôi thì vẫn đòi tiền"),
        ("Kikuri", "Thôi nào lấy đàn ra và chơi tiếp nào"),
        ("Seika", "Cố gắng lên đứt dây đàn là chuyện nhỏ thôi"),
    ],

    # KỊCH BẢN 4: Khách hàng đến quán đông
    [
        ("Seika", "Mọi người ơi hôm nay quán đông bất thường cần giúp đỡ"),
        ("Nijika", "Bao nhiêu khách vậy chị em có thể giúp được không"),
        ("Kita", "Em có thể phục vụ bàn em quen rồi ạ"),
        ("Ryo", "Tôi không muốn làm nhưng nếu trả tiền thì tôi sẽ giúp"),
        ("Kikuri", "Để tôi biểu diễn thu hút khách hàng cho"),
        ("Hitori", "Em có thể làm gì ạ em không biết ạ"),
        ("PA-san", "Tôi sẽ lo bên bếp các em lo bên ngoài"),
        ("Seika", "Kita em ra phục vụ bàn đi Ryo em ra bar pha chế"),
        ("Kita", "Vâng ạ em sẽ chào khách hàng thật nhiệt tình ạ"),
        ("Ryo", "Pha chế thì thêm phí phục vụ nhé 10 phần trăm"),
        ("Kikuri", "Tôi sẽ chơi guitar góc chắc sẽ thu hút nhiều người"),
        ("Hitori", "Em có thể giúp chị Nijika dọn bàn ạ"),
        ("Nijika", "Tốt Hitori đi cùng em nhé đừng lo"),
        ("Seika", "PA-san lo thêm món cho bàn số 5 bàn đó đặt trước"),
        ("PA-san", "Dạ rõ sẽ hoàn thành trong 10 phút"),
        ("Kikuri", "Mọi người ơi nghe Kikuri hát này bảo hay luôn"),
        ("Kita", "Khách bàn số 3 gọi thêm 2 cốc trà đá ạ"),
        ("Ryo", "Trà đá đang làm bảo họ cho 5 phút"),
        ("Nijika", "Hôm nay bận rồi cảm ơn mọi người đã giúp đỡ"),
        ("Seika", "Cuối ngày tôi khao mọi người bữa ăn nhé"),
    ],

    # KỊCH BẢN 5: Hitori tập đánh solo
    [
        ("Nijika", "Hitori em đã hoàn thành bài solo chưa"),
        ("Hitori", "Dạ em mới tập được một nửa thôi ạ"),
        ("Kita", "Senpai đánh thử đi cho em nghe với ạ"),
        ("Ryo", "Tôi nghĩ em nên đánh nhanh lên kẻo mất thời gian"),
        ("Kikuri", "Từ từ thôi âm nhạc cần cảm xúc đừng gấp"),
        ("PA-san", "Hitori có tài năng chỉ cần tự tin hơn"),
        ("Seika", "Tập nhiều sẽ giỏi em cứ từ từ"),
        ("Hitori", "Em sợ khi đánh trước mọi người ạ"),
        ("Nijika", "Không có gì phải sợ em là thành viên của band mà"),
        ("Kita", "Senpai đánh hay lắm em rất thích nghe senpai đánh ạ"),
        ("Ryo", "Kita đừng nịnh quá nhưng mà cũng đúng"),
        ("Kikuri", "Để tôi đánh cùng cho Hitori dễ hơn nhé"),
        ("Hitori", "Dạ em cảm ơn chị Kikuri ạ"),
        ("PA-san", "Tôi có thể thu âm để em nghe lại và sửa lỗi"),
        ("Seika", "Ý kiến hay thu âm rồi rút kinh nghiệm"),
        ("Nijika", "Bắt đầu từ nay nhé Hitori đánh trước đi"),
        ("Kita", "Em cổ vũ cho senpai ạ cố lên senpai"),
        ("Ryo", "Tôi sẽ đánh bass nền tảng em cứ tự nhiên"),
        ("Kikuri", "Ối nghe Hitori đánh mà tôi xúc động quá"),
        ("Seika", "Tốt lắm cứ giữ vậy là sẽ tiến bộ nhanh"),
    ],

    # KỊCH BẢN 6: Chuẩn bị show diễn lớn
    [
        ("Nijika", "Mọi người ơi tuần sau chúng ta có show diễn lớn"),
        ("Kita", "Thật ạ em rất mong cho hôm đó ạ"),
        ("Ryo", "Tôi cần mua bass mới bass cũ không đủ ngon"),
        ("Kikuri", "Show diễn mà không có bia thì không thể gọi là show"),
        ("Hitori", "Em sợ quá ạ nhiều người xem lắm ạ"),
        ("PA-san", "Tôi đã check âm thanh rồi sân khấu ổn định"),
        ("Seika", "Mọi người tập luyện chăm chỉ vào đừng gây thất vọng"),
        ("Nijika", "Chúng ta cần chuẩn bị ít nhất 5 bài hát"),
        ("Kita", "Em có thể hát thêm bài mới mà em tập ạ"),
        ("Ryo", "Tôi nghĩ nên chơi lại bài cũ đảm bảo chất lượng"),
        ("Kikuri", "Bài mới hay hơn lí do gì mà không chơi"),
        ("Hitori", "Em nghĩ mình nên tập thêm ạ"),
        ("Seika", "Tập lịch là 3 buổi tuần bắt buộc có mặt"),
        ("Nijika", "Em sẽ gửi lịch tập cho mọi người sau"),
        ("Kita", "Em sẽ cố gắng tập mỗi ngày ạ"),
        ("Ryo", "Tôi chỉ tập khi có tiền không có tiền thì không tập"),
        ("Kikuri", "Thôi tôi uống trước một chai cho có cảm hứng"),
        ("PA-san", "Kikuri đừng uống trước khi diễn mất chuẩn"),
        ("Seika", "Ai trễ tập sẽ bị phạt dọn dẹp quán 1 tuần"),
        ("Hitori", "Em sẽ đến đúng giờ ạ em hứa ạ"),
    ],

    # KỊCH BẢN 7: Tranh cãi thể loại nhạc
    [
        ("Nijika", "Chúng ta cần quyết định thể loại cho bài mới"),
        ("Kita", "Em thích pop ạ nó vui và dễ tiếp cận"),
        ("Ryo", "Pop là vô thưởng tôi thích rock hơn"),
        ("Kikuri", "Rock mới là âm nhạc thật sự còn lại đều vô ích"),
        ("Hitori", "Em thích cả hai ạ nhưng em không biết ạ"),
        ("PA-san", "Tôi nghĩ nên chọn thể loại phù hợp với band"),
        ("Seika", "Không thể theo ý một người phải thống nhất"),
        ("Nijika", "Hãy thử kết hợp cả rock và pop chúng ta sẽ thử"),
        ("Kita", "Ý hay ạ vừa có thể vui vẻ vừa mạnh mẽ"),
        ("Ryo", "Tôi không thích pop nhưng tôi sẽ theo đa số"),
        ("Kikuri", "Thôi được rồi rock pha pop cũng tạm chấp nhận được"),
        ("Hitori", "Em nghĩ chúng ta có thể viết bài mới mà ạ"),
        ("Seika", "Hôm nay mọi người về viết phần của mình đi"),
        ("Nijika", "Tuần sau mang bản nhạc đến chúng ta sẽ ghép"),
        ("Kita", "Em có thể viết lời ạ em có sẵn ý tưởng rồi"),
        ("Ryo", "Tôi viết phần bass đảm bảo sẽ chất"),
        ("Kikuri", "Tôi viết solo guitar sẽ làm bay đầu mọi người"),
        ("Hitori", "Em sẽ viết phần rhythm guitar ạ"),
        ("PA-san", "Tôi sẽ hỗ trợ mix và master bản thử"),
        ("Seika", "Tốt cứ thế nào đi cố gắng hoàn thành đúng hạn"),
    ],

    # KỊCH BẢN 8: Ngày mưa hủy show
    [
        ("Nijika", "Mọi người ơi bên ngoài mưa to quá show có thể bị hủy"),
        ("Kita", "Ối trời em đã chuẩn bị trang phục mới rồi ạ"),
        ("Ryo", "Mất tiền rồi tôi đã mua bass mới cho show này"),
        ("Kikuri", "Mưa thì mưa tôi vẫn biểu diễn được không vấn đề gì"),
        ("Hitori", "Em cũng chuẩn bị lâu rồi ạ hơi tiếc ạ"),
        ("Seika", "Quản lý nói show đã thông báo hủy an toàn là trên hết"),
        ("PA-san", "Thiết bị âm thanh không thể dùng trong thời tiết này"),
        ("Nijika", "Chúng ta có thể dời lịch sang tuần sau"),
        ("Kita", "Vâng ạ em có thể chờ đến tuần sau được ạ"),
        ("Ryo", "Nhưng tôi đã trả tiền thuê bass rồi phí hoàn lại không"),
        ("Kikuri", "Thôi tôi về uống bia một mình vậy buồn quá"),
        ("Hitori", "Chị Kikuri đừng buồn ạ tuần sau chúng ta sẽ chơi vui"),
        ("Seika", "Đúng tuần sau thời tiết sẽ tốt hơn nhiều"),
        ("Nijika", "Chúng ta có thể dùng thời gian này để tập luyện thêm"),
        ("Kita", "Ý hay ạ em có thể tập hát bài mới ạ"),
        ("Ryo", "Tôi tập bass trong nhà không cần đến phòng tập"),
        ("Kikuri", "Tôi tập guitar khi say cảm xúc lúc đó rất thật"),
        ("Hitori", "Em sẽ tập thêm ở nhà ạ cảm ơn mọi người ạ"),
        ("PA-san", "Nếu cần mượn thiết bị cứ bảo tôi"),
        ("Seika", "Tạm từ từ còn nhiều cơ hội khác phía trước"),
    ],

    # KỊCH BẢN 9: Bàn luận trang phục
    [
        ("Nijika", "Chúng ta cần thống nhất trang phục cho show sắp tới"),
        ("Kita", "Em muốn mặc màu hồng ạ màu đó rất dễ thương"),
        ("Ryo", "Màu đen đẹp hơn tôi chỉ mặc màu đen thôi"),
        ("Kikuri", "Màu hồng mà đi rock ạ người ta cười cho"),
        ("Hitori", "Em thấy màu gì cũng được ạ nhưng đừng nổi bật quá ạ"),
        ("PA-san", "Trang phục cần đồng nhất để tạo thương hiệu"),
        ("Seika", "Tôi nghĩ mặc màu đen thêm phụ kiện màu là ok"),
        ("Nijika", "Kita em có thể mặc hồng nhưng phải đồng bộ"),
        ("Kita", "Vậy em mặc áo hồng và quần đen được không ạ"),
        ("Ryo", "Được rồi miễn là không loang loang loang loang"),
        ("Kikuri", "Tôi sẽ mặc áo đen và đeo dây chuyền sỏi"),
        ("Hitori", "Em có sẵn áo thun đen rồi ạ"),
        ("Seika", "Nhớ mang thêm đồ dự trữ để phòng trường hợp xấu"),
        ("PA-san", "Tôi sẽ chuẩn bị thêm trang phục cho ai quên mang"),
        ("Nijika", "Mọi người nhớ chụp ảnh gửi vào nhóm trước 2 ngày"),
        ("Kita", "Em sẽ chụp ạ em có mấy ảnh đẹp lắm"),
        ("Ryo", "Tôi không thích chụp ảnh nhưng thôi được"),
        ("Kikuri", "Chụp ảnh làm gì đến show diễn là đẹp rồi"),
        ("Hitori", "Em sẽ cố gắng cười tự nhiên khi chụp ạ"),
        ("Seika", "Tập trung vào chuyện chính trang phục chỉ là phụ"),
    ],

    # KỊCH BẢN 10: Ryo bị nợ tiền
    [
        ("Ryo", "Mọi người ơi tôi cần mượn ít tiền trả lại sau"),
        ("Nijika", "Ryo lại bị nợ tiền ạ lần này bao nhiêu"),
        ("Kita", "Chị Ryo mượn bao nhiêu ạ em có thể cho mượn một ít"),
        ("Kikuri", "Tôi cũng đang nợ tiền đây không giúp được rồi"),
        ("Hitori", "Em có ít tiền tiết kiệm ạ chị cần bao nhiêu ạ"),
        ("PA-san", "Ryo em cần tiền làm gì lại mua bass hả"),
        ("Seika", "Em nợ tiền đến bao giờ mới trả công nợ chồng chất"),
        ("Ryo", "Tôi cần mua dây đàn mới và trả tiền thuê phòng tập"),
        ("Nijika", "Em đã bao nhiêu lần rồi phải quản lý tài chính tốt hơn"),
        ("Kita", "Chị Ryo có thể làm thêm để kiếm tiền mà ạ"),
        ("Kikuri", "Làm thêm ạ nhạc công làm thêm khó lắm đó"),
        ("Hitori", "Em có thể cho chị mượn một ít ạ"),
        ("Seika", "Thôi để tôi ứng trước nhưng phải khấu trừ vào tiền show"),
        ("Ryo", "Cảm ơn lần này tôi sẽ trả đủ rồi"),
        ("PA-san", "Tôi nghĩ Ryo nên học cách tiết kiệm"),
        ("Nijika", "Lần sau em không cho mượn nữa đâu đừng hòng"),
        ("Kita", "Em tin chị Ryo sẽ trả mà chị chỉ cần thời gian thôi"),
        ("Kikuri", "Ryo mà quên rồi thằng nào chẳng nợ vài lần"),
        ("Hitori", "Chị Ryo cố gắng làm thêm ạ em tin chị"),
        ("Seika", "Hết rồi đi tập thôi quên chuyện tiền bạc đi"),
    ],

    # KỊCH BẢN 11: Ôn lại show thành công
    [
        ("Nijika", "Hôm qua show thành công quá cảm ơn mọi người"),
        ("Kita", "Em rất vui ạ khách hàng vỗ tay nhiệt tình lắm"),
        ("Ryo", "Cũng tạm được nhưng tôi đánh sai một chỗ"),
        ("Kikuri", "Sai gì đâu hay mà không ai nhận ra đâu"),
        ("Hitori", "Em thấy mình đánh sai nhiều chỗ ạ xin lỗi ạ"),
        ("PA-san", "Chất lượng âm thanh tốt không có sự cố gì"),
        ("Seika", "Kessoku Band tiến bộ quá tiếp tục phát huy"),
        ("Nijika", "Chúng ta nhận được lời mời cho show tiếp theo rồi"),
        ("Kita", "Thật ạ em sẽ tập luyện nhiều hơn ạ"),
        ("Ryo", "Lần này tôi sẽ không đánh sai nữa họa lại thế"),
        ("Kikuri", "Tôi sẽ uống ít lại để chơi chính xác hơn"),
        ("Hitori", "Em sẽ tập thêm ở nhà để tốt hơn ạ"),
        ("PA-san", "Tôi sẽ cải thiện hệ thống âm thanh hiện tại"),
        ("Seika", "Tôi sẽ đặt lịch tập thêm cho tháng sau"),
        ("Nijika", "Chúng ta có thể viết thêm bài mới cho lần sau"),
        ("Kita", "Em có ý tưởng cho bài mới rồi ạ"),
        ("Ryo", "Bài mới của tôi cũng đang hoàn thiện"),
        ("Kikuri", "Tuyệt vời Kessoku Band sẽ ngày càng lớn mạnh"),
        ("Hitori", "Em sẽ cố gắng không phụ lòng tin mọi người ạ"),
        ("Seika", "Nghỉ ngơi đi mai còn nhiều việc phía trước"),
    ],

    # KỊCH BẢN 12: Ngày sinh nhật Nijika
    [
        ("Kita", "Mai là sinh nhật chị Nijika rồi chúng ta nên tổ chức gì đó"),
        ("Ryo", "Tôi không có tiền mua quà nhưng có thể chơi miễn phí"),
        ("Kikuri", "Để tôi mua bia về chúng ta ăn mừng"),
        ("Hitori", "Em có thể tự làm bánh ạ em biết làm một chút ạ"),
        ("Seika", "Đừng lo tôi sẽ lo phần nước uống và đồ ăn"),
        ("PA-san", "Tôi sẽ trang trí phòng tập đảm bảo sẽ đẹp"),
        ("Nijika", "Sao hôm nay mọi người nhìn em kì thế có chuyện gì ạ"),
        ("Kita", "Không có gì ạ em chỉ thấy hôm nay chị đẹp quá thôi ạ"),
        ("Ryo", "Nijika ngày mai em đến phòng tập sớm nhé có việc gấp"),
        ("Kikuri", "Ừng ừng rất gấp không thể trễ được đâu"),
        ("Hitori", "Dạ mai em cũng có chuyện cần nói ạ"),
        ("Seika", "Tôi cũng cần gặp Nijika để bàn công việc quán"),
        ("Nijika", "Mọi người bị gì vậy em thấy khá là lạ ạ"),
        ("Kita", "Mai rồi chị sẽ biết ạ bí mật nhớ giữ kín nhé"),
        ("Ryo", "Tôi không giỏi giữ bí mật nhưng có gấp"),
        ("Kikuri", "Thôi tôi về trước mai gặp lại nhé"),
        ("Hitori", "Em cũng về làm bánh đây ạ"),
        ("PA-san", "Tôi cũng về chuẩn bị đồ trang trí"),
        ("Seika", "Để tôi đóng cửa quán rồi đi mua đồ"),
        ("Nijika", "Mọi người hôm nay là lạ quá em rất tò mò"),
    ],

    # KỊCH BẢN 13: Sinh nhật Nijika chính thức
    [
        ("Kita", "Mừng sinh nhật chị Nijika ạ chúc chị luôn vui vẻ"),
        ("Ryo", "Sinh nhật vui vẻ tôi không có tiền mua quà nhưng chơi tặng"),
        ("Kikuri", "Sinh nhật vui vẻ nào uống bia mừng đi"),
        ("Hitori", "Chúc chị sinh nhật vui vẻ ạ em tự làm bánh ạ"),
        ("Nijika", "Ối trời mọi người làm bất ngờ em quá cảm ơn mọi người"),
        ("Seika", "Chúc em tuổi mới nhiều sức khỏe và thành công"),
        ("PA-san", "Chúc Nijika luôn là người chị tốt của band"),
        ("Kita", "Chị thử nếm bánh senpai Hitori làm đi ạ"),
        ("Nijika", "Để em ăn thử nào trời ngon quá Hitori"),
        ("Hitori", "Dạ em vui quá ạ em sợ không ngon ạ"),
        ("Ryo", "Hitori nấu ăn tốt đấy sau này mở quán ăn đi"),
        ("Kikuri", "Đừng đùa Hitori mà mở quán ăn chắc bán đông"),
        ("Seika", "Uống bia vừa thôi Kikuri hôm nay không phải diễn"),
        ("PA-san", "Nijika em có muốn lên sân khấu chơi vài bài không"),
        ("Nijika", "Hôm nay em được nghỉ mà nhưng thôi chơi vài bài cũng vui"),
        ("Kita", "Em đánh guitar cho chị Nijika hát ạ"),
        ("Ryo", "Tôi bass nhanh gọn nhé chơi xong tôi về"),
        ("Kikuri", "Tôi cũng tham gia nữa hôm nay vui quá"),
        ("Hitori", "Em cũng sẽ tham gia ạ hôm nay em cảm thấy tự tin ạ"),
        ("Seika", "Vậy thì bắt đầu thôi Kessoku Band ơi"),
    ],

    # KỊCH BẢN 14: Kikuri say rượu
    [
        ("Kikuri", "Ối hôm nay đẹp quá chúng ta uống đi mọi người"),
        ("Nijika", "Chị Kikuri lại say rồi mới có sáng sớm mà"),
        ("Kita", "Chị uống nhiều quá hại lắm ạ ảnh hưởng đến giọng hát"),
        ("Ryo", "Để tôi uống cùng nhưng tôi không trả tiền đâu"),
        ("Hitori", "Chị Kikuri có ổn không ạ em lo quá ạ"),
        ("PA-san", "Kikuri em về nhà nghỉ đi hôm nay không thể tập"),
        ("Seika", "Lại thế nữa rồi em có thể tiết chế được không"),
        ("Kikuri", "Em tiết chế rồi ạ hôm nay em mới uống 3 chai thôi"),
        ("Nijika", "3 chai mà còn bảo tiết chế trời ơi"),
        ("Kita", "Để em pha trà gừng cho chị giải rượu ạ"),
        ("Ryo", "Để tôi lấy nước cho Kikuri uống đi"),
        ("Kikuri", "Không uống nước uống nước nhạt lắm để tôi uống bia"),
        ("Hitori", "Chị ơi đừng uống nữa ạ em xin chị ạ"),
        ("Seika", "Kikuri em có muốn bị cấm diễn không"),
        ("Kikuri", "Em xin lỗi ạ em sẽ uống ít lại ạ"),
        ("PA-san", "Em nói thế nhưng chẳng bao giờ làm"),
        ("Nijika", "Thôi để chị về ngủ một giấc đi tỉnh rồi quay lại"),
        ("Kita", "Để em đưa chị về ạ em biết nhà chị mà"),
        ("Ryo", "Kikuri hôm sau uống ít thôi nói trước để tôi không đi"),
        ("Hitori", "Chị Kikuri đi nghỉ ngơi ạ hôm nay nghỉ tập ạ"),
    ],

    # KỊCH BẢN 15: Hitori tập nói với fan
    [
        ("Nijika", "Hitori em cần tập nói chuyện với fan khi có show"),
        ("Hitori", "Em sợ ạ em không biết nói gì ạ"),
        ("Kita", "Không có gì phải sợ ạ chỉ cần nói cảm ơn là được ạ"),
        ("Ryo", "Tôi cũng không thích nói chuyện nhưng phải làm"),
        ("Kikuri", "Cứ tự nhiên nghĩ họ là bạn thân mà nói"),
        ("PA-san", "Giao tiếp với fan là kỹ năng quan trọng"),
        ("Seika", "Em có thể tập trước gương rồi từ từ sẽ quen"),
        ("Nijika", "Thử nói câu đơn giản trước em tập đi"),
        ("Hitori", "Cảm ơn mọi người đã đến nghe chúng tôi chơi ạ"),
        ("Kita", "Tốt rồi ạ nhưng cười lên một chút cho tự nhiên ạ"),
        ("Ryo", "Cười hay không cười cũng được miễn là có nói là ok"),
        ("Kikuri", "Nijika từ từ Hitori sẽ làm được"),
        ("Seika", "Tập thêm lần nữa em sẽ quen thôi"),
        ("Hitori", "Em rất vui khi được chơi cho mọi người nghe ạ"),
        ("Nijika", "Tốt hơn rồi nhìn vào mắt fan khi nói nhé"),
        ("Kita", "Đúng vậy ạ fan sẽ cảm thấy được quan tâm ạ"),
        ("Ryo", "Nếu em không dám nhìn thì nhìn vào trần cũng được"),
        ("Kikuri", "Nhìn vào bia cũng ok tôi vẫn làm thế"),
        ("Hitori", "Em sẽ tập thêm ạ cảm ơn mọi người chỉ bảo ạ"),
        ("PA-san", "Có gắng là sẽ tiến bộ tự tin lên em"),
    ],

    # KỊCH BẢN 16: Sự cố thiết bị âm thanh
    [
        ("PA-san", "Âm thanh có vấn đề hình như dây loa bị hỏng"),
        ("Nijika", "Sao lại hỏng được hôm qua còn dùng tốt mà"),
        ("Kita", "Có sửa được không ạ hay cần mua mới"),
        ("Ryo", "Tôi biết chỗ sửa loa nhưng giá cao lắm"),
        ("Kikuri", "Loa hỏng thì đánh acoustic đi cũng chất"),
        ("Hitori", "Em có thể đưa đàn acoustic của em ạ"),
        ("Seika", "Không thể đánh acoustic cho show sắp tới được"),
        ("PA-san", "Để tôi kiểm tra lại dây điện trước đã"),
        ("Nijika", "Cần gấp thiết bị thay thế không là trễ show"),
        ("Kita", "Em có quen bên cho thuê thiết bị ạ"),
        ("Ryo", "Giá thuê là bao nhiêu tôi có thể thương lượng"),
        ("Kikuri", "Thuê thì thuê đừng loằng ngoằng nữa mất thời gian"),
        ("Hitori", "Em có thể dùng một phần tiền tiết kiệm để giúp ạ"),
        ("Seika", "Không cần quán tài trợ cho để tôi lo"),
        ("PA-san", "Dây điện không có vấn đề có thể là do loa già"),
        ("Nijika", "Vậy cần mua loa mới ai biết chỗ mua uy tín"),
        ("Kita", "Em biết một chỗ bán đồ cũ chất lượng tốt ạ"),
        ("Ryo", "Để tôi đi xem với tôi rảnh"),
        ("Kikuri", "Mua loa mới show lần sau sẽ hoành tráng hơn"),
        ("Hitori", "Em cũng muốn đi theo ạ để học hỏi thêm ạ"),
    ],

    # KỊCH BẢN 17: Ôn tập cho cuộc thi
    [
        ("Nijika", "Chúng ta được chọn tham gia cuộc thi tài năng hả"),
        ("Kita", "Ối thật ạ em rất vui ạ nhất định phải thắng"),
        ("Ryo", "Cuộc thi thì có thưởng không không thưởng tôi không đi"),
        ("Kikuri", "Có thưởng nhé ít nhất cũng phải có bia"),
        ("Hitori", "Em sợ ạ thi tài năng có đông người xem ạ"),
        ("PA-san", "Cuộc thi lớn cần chuẩn bị kĩ lưỡng"),
        ("Seika", "Tôi đã nhận được thể lệ rồi giải thưởng rất giá trị"),
        ("Nijika", "Chúng ta cần tập thêm giờ không thể bằng lòng"),
        ("Kita", "Em sẵn sàng tập mỗi ngày ạ em không ngại"),
        ("Ryo", "Tôi tập bass thêm cam đoan sẽ không sai"),
        ("Kikuri", "Tôi sẽ viết thêm đoạn solo mới đảm bảo gây sock"),
        ("Hitori", "Em sẽ tập rhythm guitar thật tốt ạ"),
        ("PA-san", "Tôi sẽ đảm bảo âm thanh tốt nhất cho phần thi"),
        ("Seika", "Trang phục cũng cần chuẩn bị gây ấn tượng"),
        ("Nijika", "Chúng ta sẽ chơi bài hay nhất của band"),
        ("Kita", "Bài hay nhất chắc là bài em viết ạ"),
        ("Ryo", "Bài của tao mới hay đừng cưới"),
        ("Kikuri", "Bài nào cũng hay cả nhưng bài có solo mới nhất"),
        ("Hitori", "Em nghĩ chúng ta chơi bài mọi người đều thích ạ"),
        ("Seika", "Thống nhất chơi bài cuối cùng của band đó là bài hay nhất"),
    ],

    # KỊCH BẢN 18: Ngày tập trượt dài
    [
        ("Nijika", "Hôm nay thời tiết xấu quá nhưng vẫn phải tập"),
        ("Kita", "Em đi đến phòng tập rồi ạ đường ướt hết"),
        ("Ryo", "Tôi bị ướt hết quần áo cần mượn đồ mặc"),
        ("Kikuri", "Mưa buồn quá hay uống chiêu đi cho ấm người"),
        ("Hitori", "Em đi xe đạp đến ạ ướt hết người rồi ạ"),
        ("PA-san", "Tôi mang theo khăn tắm ai cần dùng thì lấy"),
        ("Seika", "Mưa nhưng tập vẫn diễn ra không được nghỉ"),
        ("Nijika", "Mọi người lau khô người rồi bắt đầu tập nhé"),
        ("Kita", "Vâng ạ em lau rồi sẵn sàng tập ạ"),
        ("Ryo", "Tôi muốn đồ của ai đó không thể mặc đồ ướt"),
        ("Kikuri", "Để tôi cho mượn áo khoác Ryo mặc tạm đi"),
        ("Hitori", "Em có áo mưa dựa theo ạ chị có cần không ạ"),
        ("Seika", "Tốt có dự bị vậy mới là người chuyên nghiệp"),
        ("Nijika", "Hôm nay tập trung vào bài mới không được phân tâm"),
        ("Kita", "Em đã thuộc lời rồi ạ chị chỉ cần nói nhạc là ok"),
        ("Ryo", "Bass của tôi bị ẩm do mưa âm thanh có thể không tốt"),
        ("Kikuri", "Để tôi kiểm tra giúp tôi biết sửa một chút"),
        ("Hitori", "Em cũng bị ẩm dây ạ nhưng em có máy sấy ạ"),
        ("PA-san", "Để tôi lấy máy sấy cho đừng để dây bị hỏng"),
        ("Seika", "Cố gắng tập xong hôm nay tuần sau có show rồi"),
    ],

    # KỊCH BẢN 19: Khách khen Hitori
    [
        ("Seika", "Hitori có khách khen em đánh guitar hay lắm"),
        ("Hitori", "Dạ thật ạ em cảm ơn ạ"),
        ("Nijika", "Em thấy chưa tài năng của em được công nhận rồi"),
        ("Kita", "Senpai đánh hay mà em đã nói rồi ạ"),
        ("Ryo", "Khen ít thôi kẻo Hitori sinh lòng kiêu"),
        ("Kikuri", "Hitori đánh hay thật mà tôi cũng phải công nhận"),
        ("PA-san", "Em cứ tự tin lên em có năng khiếu"),
        ("Seika", "Khách còn hỏi em có nhận dạy kèm không"),
        ("Hitori", "Em không biết dạy ai ạ em chỉ biết đánh thôi ạ"),
        ("Nijika", "Sao lại không em có thể dạy những người mới tập"),
        ("Kita", "Em cũng muốn học thêm từ senpai ạ"),
        ("Ryo", "Dạy kèm kiếm tiền tốt lắm Hitori nên thử"),
        ("Kikuri", "Đúng đó vừa được chơi đàn vừa có tiền"),
        ("Hitori", "Em sợ không dạy được ạ em không giỏi giao tiếp ạ"),
        ("Seika", "Từ từ rồi em sẽ quen hôm nay em hãy nhận lời đi"),
        ("PA-san", "Cố gắng lên một bước nhỏ cho sự tự tin"),
        ("Nijika", "Em tin Hitori làm được mà"),
        ("Kita", "Senpai có thể ạ em ủng hộ senpai"),
        ("Ryo", "Nếu em dạy kèm nhớ giới thiệu tôi làm quản lý"),
        ("Kikuri", "Thôi để Hitori tự quyết định đừng gây áp lực"),
    ],

    # KỊCH BẢN 20: Tranh cãi lịch tập
    [
        ("Nijika", "Chúng ta cần thống nhất lịch tập cho tháng sau"),
        ("Kita", "Em rảnh thứ 3 và thứ 5 sau giờ học ạ"),
        ("Ryo", "Tôi chỉ rảnh thứ 7 và chủ nhật còn lại bận"),
        ("Kikuri", "Tôi hôm nào cũng được chỉ cần báo trước"),
        ("Hitori", "Em rảnh thứ 2 thứ 4 và thứ 6 ạ"),
        ("PA-san", "Tôi làm theo lịch của quán thứ 7 phải đi làm"),
        ("Seika", "Khó quá mọi người đều bận giờ khác nhau"),
        ("Nijika", "Hãy chọn thứ 3 và thứ 6 đi theo đa phần đông"),
        ("Kita", "Thứ 3 em ổn ạ nhưng thứ 6 em có thể sắp xếp"),
        ("Ryo", "Thứ 6 tôi bận không thể dời được"),
        ("Kikuri", "Vậy thứ 3 và thứ 7 đi Kikuri ổn hết"),
        ("Hitori", "Em thứ 7 cũng được ạ không vấn đề ạ"),
        ("Seika", "Thứ 3 và chủ nhật tôi thấy hợp lý nhất"),
        ("PA-san", "Chủ nhật tôi rảnh có thể tập cả ngày"),
        ("Nijika", "Vậy thứ 3 và chủ nhật nhé thống nhất nha"),
        ("Kita", "Vâng ạ em sẽ sắp xếp thời gian ạ"),
        ("Ryo", "Được rồi thứ 3 và chủ nhật tôi sẽ có mặt"),
        ("Kikuri", "Tuyệt chủ nhật tập xong đi uống bia nhé"),
        ("Hitori", "Em cũng sẽ có mặt đúng giờ ạ"),
        ("Seika", "Nhất trí rồi không được trễ ai trễ sẽ bị phạt"),
    ],

    # KỊCH BẢN 21: Chuẩn bị phỏng vấn
    [
        ("Nijika", "Mọi người ơi có báo chí muốn phỏng vấn band mình"),
        ("Kita", "Ối trời thật ạ em phải mặc gì đây"),
        ("Ryo", "Phỏng vấn thì có được trả tiền không"),
        ("Kikuri", "Phỏng vấn ạ chắc họ muốn hỏi về âm nhạc"),
        ("Hitori", "Em sợ bị hỏi ạ em không biết trả lời ạ"),
        ("PA-san", "Coi là cơ hội tốt để quảng bá band"),
        ("Seika", "Chuẩn bị trước câu trả lời đừng để bị động"),
        ("Nijika", "Chúng ta cần phân công ai trả lời câu gì"),
        ("Kita", "Em có thể trả lời về giọng hát và cảm xúc ạ"),
        ("Ryo", "Tôi trả lời về tài chính và hợp đồng"),
        ("Kikuri", "Tôi trả lời về cảm hứng âm nhạc và rượu"),
        ("Hitori", "Em có thể trả lời về kỹ thuật đánh đàn ạ"),
        ("Seika", "Tôi và PA-san sẽ trả lời về mặt quản lý"),
        ("PA-san", "Đồng ý tôi sẽ nói về âm thanh và thiết bị"),
        ("Nijika", "Tập duyệt thử đi tôi sẽ đóng vai phóng viên"),
        ("Kita", "Thử nhất senpai Hitori trả lời trước đi ạ"),
        ("Hitori", "Em cảm ơn cơ hội chúng tôi là Kessoku Band ạ"),
        ("Ryo", "Tốt Hitori làm tốt đấy chứ"),
        ("Kikuri", "Tự nhiên như đang nói chuyện với bạn"),
        ("Seika", "Cứ giữ tinh thần này buổi phỏng vấn sẽ thành công"),
    ],

    # KỊCH BẢN 22: Hitori biến mất
    [
        ("Nijika", "Mọi người ơi Hitori đâu rồi không thấy đến tập"),
        ("Kita", "Em gọi điện nhưng không nghe máy ạ"),
        ("Ryo", "Chắc lại trốn ở xó nào rồi quên thôi"),
        ("Kikuri", "Để tôi đi tìm quanh đây chắc không xa đâu"),
        ("PA-san", "Em ấy hay bị lo lắng trước buổi tập"),
        ("Seika", "Tìm em ấy đi đừng để em ấy một mình"),
        ("Nijika", "Kita em đi tìm ở nhà vệ sinh đi"),
        ("Kita", "Vâng ạ em đi tìm ngay ạ"),
        ("Ryo", "Tôi đi tìm ở nhà kho em ấy hay trốn ở đó"),
        ("Kikuri", "Tôi đi tìm ở ngoài sân hôm qua thấy em ấy ở đó"),
        ("PA-san", "Nếu không thấy tôi sẽ tìm ở tầng hầm"),
        ("Seika", "Nijika em ở lại phòng cho phòng khi em ấy về"),
        ("Kita", "Ối tìm thấy rồi ạ em ấy ở trong tủ quần áo ạ"),
        ("Nijika", "Hitori sao em lại trốn ở đó mọi người lo lắm"),
        ("Hitori", "Em xin lỗi ạ em sợ tập bài mới quá ạ"),
        ("Kikuri", "Không có gì phải sợ chúng ta sẽ tập từ từ"),
        ("Ryo", "Ra đi đừng làm mất thời gian nữa"),
        ("Kita", "Senpai ơi em ở đây mà đừng lo ạ"),
        ("PA-san", "Tìm thấy là tốt rồi bắt đầu tập thôi"),
        ("Seika", "Lần sau đừng trốn nữa có gì nói ra nhé"),
    ],

    # KỊCH BẢN 23: Bàn luận bài hát mới
    [
        ("Nijika", "Chúng ta cần viết bài mới cho album sắp tới"),
        ("Kita", "Em có một số ý tưởng về tình bạn ạ"),
        ("Ryo", "Tình bạn là chủ đề nhạt viết về nó thì không hay"),
        ("Kikuri", "Viết về cuộc sống đi thả hơn nhiều"),
        ("Hitori", "Em có thể viết về nỗi buồn và cô đơn ạ"),
        ("PA-san", "Kết hợp cả buồn lẫn vui tạo sự tương phản"),
        ("Seika", "Bài hát cần có thông điệp đừng viết vô thưởng"),
        ("Nijika", "Mọi người viết phần của mình tuần sau góp lại"),
        ("Kita", "Em viết lời ạ em có thể viết về tình yêu"),
        ("Ryo", "Tôi viết phần bass đảm bảo sẽ chất"),
        ("Kikuri", "Tôi viết solo guitar sẽ làm bay người nghe"),
        ("Hitori", "Em viết rhythm guitar ạ và có thể viết thêm ạ"),
        ("Seika", "Đừng quên phần điệp khúc điệp khúc quan trọng nhất"),
        ("Nijika", "Điệp khúc để cho em viết em có ý rồi"),
        ("Kita", "Điệp khúc cần bắt tai và dễ nhớ ạ"),
        ("Ryo", "Điệp khúc mà nhạt là thất bại cố gắng lên"),
        ("Kikuri", "Để tôi nghiên cứu thêm một chút về điệp khúc"),
        ("Hitori", "Em nghe thử bản thử của mọi người rồi góp ý ạ"),
        ("PA-san", "Tôi sẽ thu âm bản nháp để dễ chỉnh sửa"),
        ("Seika", "Bắt đầu thôi thời gian không chờ ai cả"),
    ],

    # KỊCH BẢN 24: Ryo bị mất dây đàn
    [
        ("Ryo", "Ai đó lấy dây đàn của tôi hôm qua còn để đây"),
        ("Nijika", "Em có để trong phòng tập không hay quên ở nhà"),
        ("Kita", "Để em giúp chị tìm ạ chị còn nhớ để ở đâu không"),
        ("Kikuri", "Tôi thấy hôm qua Ryo để trong góc phòng tập mà"),
        ("Hitori", "Em thấy chị để trên ghế ạ lúc chúng ta ra về ạ"),
        ("PA-san", "Để tôi kiểm tra camera quan sát trong phòng"),
        ("Seika", "Ai đó có thể đã lấy nhầm để tôi hỏi mọi người"),
        ("Ryo", "Dây đàn đó đắt tiền lắm tôi cần nó gấp"),
        ("Nijika", "Em nhớ hôm qua thấy Hitori cầm về có không Hitori"),
        ("Hitori", "A em xin lỗi ạ em cầm nhầm ạ để em về lấy ạ"),
        ("Kita", "Senpai cầm nhầm dây của chị Ryo ạ"),
        ("Kikuri", "Hai cây đàn giống nhau quá nên nhầm là chuyện thường"),
        ("Ryo", "Hitori trả lại dây đừng làm tôi lo lắng"),
        ("Hitori", "Em xin lỗi nhiều ạ em sẽ về lấy ngay ạ"),
        ("Nijika", "Em đi với Hitori cho an toàn nhé"),
        ("Kita", "Em cũng đi ạ để giúp senpai mang dây ạ"),
        ("Ryo", "Đi nhanh về nhanh tôi cần nó để tập"),
        ("Kikuri", "Thôi nhé tìm thấy là tốt rồi đừng gây hoang mang"),
        ("Seika", "Lần sau để ý hơn đừng để nhầm lẫn nữa"),
        ("PA-san", "Kết thúc tốt đẹp tiếp tục tập thôi"),
    ],

    # KỊCH BẢN 25: Đi chơi cùng nhau
    [
        ("Nijika", "Hôm nay nghỉ tập chúng ta đi chơi cùng nhau nhé"),
        ("Kita", "Em thích ạ đi công viên chơi không ạ"),
        ("Ryo", "Đi chơi thì tốt nhưng ai trả tiền"),
        ("Kikuri", "Để tôi bảo đi đến quán bia đi vừa chơi vừa uống"),
        ("Hitori", "Em thích đi công viên ạ có nhiều cây xanh ạ"),
        ("PA-san", "Tôi nghĩ đi ăn uống thì thực tế hơn"),
        ("Seika", "Đi công viên trước tôi sẽ lo đồ ăn trưa"),
        ("Nijika", "Ý kiến hay đi công viên rồi đi ăn"),
        ("Kita", "Em sẽ mang máy ảnh đi chụp hình ạ"),
        ("Ryo", "Chụp hình làm gì tốn pin đi ăn là chính"),
        ("Kikuri", "Chụp hình để kỷ niệm sau này coi lại vui"),
        ("Hitori", "Em có thể chụp cùng mọi người được không ạ"),
        ("Seika", "Đi thôi đừng đứng ở đây nói chuyện nữa"),
        ("PA-san", "Tôi sẽ lái xe cho mọi người lên xe đi"),
        ("Nijika", "Hôm nay trời đẹp quá hợp lý để đi chơi"),
        ("Kita", "Em ngồi cạnh cửa sổ ạ em thích ngắm cảnh"),
        ("Ryo", "Tôi ngồi sau buồn ngủ một chút"),
        ("Kikuri", "Mở nhạc lên đi đi chơi phải có nhạc"),
        ("Hitori", "Em có thể chọn nhạc ạ em muốn nghe bài nhẹ ạ"),
        ("Seika", "Ok bật nhạc lên và đi thôi nào"),
    ],

    # KỊCH BẢN 26: Tập trên sân khấu lớn
    [
        ("PA-san", "Sân khấu lớn khác với phòng tập các em phải thích ứng"),
        ("Nijika", "Âm thanh ở đây rất khác cần chỉnh lại"),
        ("Kita", "Em thấy hơi một chút nhưng em sẽ quen ạ"),
        ("Ryo", "Bass của tôi cần chỉnh lại equalizer"),
        ("Kikuri", "Guitar của tôi nghe rộng quá cần thêm effect"),
        ("Hitori", "Em thấy âm thanh guitar của em bị mất ạ"),
        ("Seika", "PA-san lo phần âm thanh đi chúng tôi chuẩn bị diễn"),
        ("PA-san", "Để tôi chỉnh lại các em đợi một chút"),
        ("Nijika", "Kita em thử hát đi để chỉnh volume"),
        ("Kita", "Vâng ạ em hát thử nhé ạ la la la"),
        ("Ryo", "Volume guitar của Hitori thấp quá lên tiếng đi"),
        ("Hitori", "Dạ em chỉnh lên rồi ạ có được không ạ"),
        ("Kikuri", "Ok nghe tốt rồi giờ tôi chỉnh solo"),
        ("PA-san", "Bass của Ryo hơi bé tôi mở lên một chút"),
        ("Ryo", "Ok cảm ơn giờ nghe được rồi"),
        ("Nijika", "Chúng ta chạy thử cả bài đi xem thế nào"),
        ("Kita", "Sẵn sàng ạ đếm 1 2 3 4"),
        ("Hitori", "Em sẵn sàng rồi ạ bắt đầu thôi ạ"),
        ("Kikuri", "Chơi nhiệt vào sân khấu lớn mà phải tỏa sáng"),
        ("Seika", "Tuyện vời âm thanh tốt có thể bắt đầu diễn được rồi"),
    ],

    # KỊCH BẢN 27: Hitori nhận quà từ fan
    [
        ("Kita", "Senpai Hitori có fan gửi quà cho senpai nè ạ"),
        ("Hitori", "Thật ạ ai gửi vậy ạ em không biết ạ"),
        ("Nijika", "Mở ra xem đi chắc là quà động viên đó"),
        ("Ryo", "Tôi cũng muốn có fan gửi quà nhưng không ai gửi"),
        ("Kikuri", "Hitori nổi tiếng rồi có fan là chuyện thường"),
        ("Hitori", "Em mở ra ạ ối trời là một chiếc kẹp tóc ạ"),
        ("Seika", "Đẹp đấy fan biết em thích kẹp tóc hả"),
        ("Kita", "Đẹp quá ạ senpai đeo lên đi ạ"),
        ("Hitori", "Em cảm ơn fan nhiều ạ em sẽ đeo ạ"),
        ("PA-san", "Em xem có thư gửi kèm không đọc thư đi"),
        ("Hitori", "Dạ fan nói là cảm ơn em đã truyền cảm hứng ạ"),
        ("Nijika", "Em thấy chưa âm nhạc của em có ảnh hưởng đến người khác"),
        ("Kikuri", "Cảm giác tốt phải không có động lực để tiếp tục"),
        ("Ryo", "Tôi cũng muốn có cảm giác đó nhưng thôi"),
        ("Kita", "Chị Ryo đừng buồn ạ em là fan của chị mà ạ"),
        ("Ryo", "Cảm ơn Kita nhưng tôi muốn fan thật cơ"),
        ("Hitori", "Em sẽ cố gắng nhiều hơn để xứng đáng ạ"),
        ("Seika", "Cứ cố gắng fan sẽ ngày càng nhiều thôi"),
        ("PA-san", "Hitori nên trả lời cảm ơn fan bằng một tin nhắn"),
        ("Hitori", "Dạ em sẽ nhắn tin cảm ơn fan ạ"),
    ],

    # KỊCH BẢN 28: Seika kế hoạch mở rộng
    [
        ("Seika", "Tôi có kế hoạch phát triển quán rộng hơn"),
        ("Nijika", "Chị định làm gì ạ em có thể giúp không"),
        ("Kita", "Quán mở rộng ạ tuyệt quá sẽ có nhiều khách hơn"),
        ("Ryo", "Mở rộng cần vốn chúng ta lấy tiền ở đâu"),
        ("Kikuri", "Để tôi chơi nhạc đường phố quyên góp"),
        ("Hitori", "Em có thể giúp trang trí quán ạ"),
        ("PA-san", "Tôi có thể cải thiện hệ thống âm thanh cho quán"),
        ("Seika", "Tôi đã có kế hoạch cụ thể cần mọi người hợp tác"),
        ("Nijika", "Chị nói đi em sẽ nghe và góp ý"),
        ("Kita", "Em nghĩ mình nên tăng thêm khu vận động ạ"),
        ("Ryo", "Khu vận động tốn diện tích không hiệu quả"),
        ("Kikuri", "Khu bia thì được khách đến uống sẽ nhiều hơn"),
        ("Hitori", "Em thấy cần một góc yên tĩnh cho người muốn riêng tư ạ"),
        ("Seika", "Ý Hitori hay đó một góc riêng tư cho khách"),
        ("PA-san", "Có thể cải thiện âm thanh ở khu vực biểu diễn"),
        ("Nijika", "Em sẽ lo phần marketing và truyền thông"),
        ("Kita", "Em có thể đăng bài lên mạng xã hội ạ"),
        ("Ryo", "Tôi lo phần tài chính đảm bảo không lỗ vốn"),
        ("Kikuri", "Còn tôi lo phần giải trí đảm bảo khách sẽ quay lại"),
        ("Hitori", "Em làm bất cứ việc gì cần ạ"),
    ],

    # KỊCH BẢN 29: Phân chia tiền show
    [
        ("Ryo", "Tôi nghĩ tiền show nên chia theo tỷ lệ đóng góp"),
        ("Nijika", "Nhưng mọi người đều đóng góp công bằng mà"),
        ("Kita", "Em chỉ cần đủ tiền đi lại là được ạ"),
        ("Kikuri", "Tôi nghĩ nên chia đều ai cũng quan trọng"),
        ("Hitori", "Em thấy chia thế nào cũng được ạ"),
        ("Seika", "Tôi là người quản lý tôi sẽ quyết định"),
        ("PA-san", "Đóng góp công bằng là đúng chia đều mới tốt"),
        ("Ryo", "Nhưng tôi chơi bass chính tôi xứng đáng hơn"),
        ("Nijika", "Rồi em ấy nói đúng ai cũng có vai trò riêng"),
        ("Kita", "Vâng ạ thiếu bất kỳ ai band sẽ không hoàn hảo"),
        ("Kikuri", "Đúng band là tập thể phải đoàn kết"),
        ("Hitori", "Em đồng ý với chị Nijika ạ"),
        ("Seika", "Chia đều cho 7 người không ai được hơn ai"),
        ("Ryo", "Thật không công bằng nhưng tôi sẽ nghe theo"),
        ("PA-san", "Tốt vậy mọi người đều vui vẻ"),
        ("Nijika", "Cảm ơn chị Seika đã quyết định công bằng"),
        ("Kita", "Em thấy mọi người đều xứng đáng như nhau ạ"),
        ("Kikuri", "Tôi uống bằng tiền show này chắc say mập luôn"),
        ("Hitori", "Em sẽ dùng số tiền này để mua phụ kiện đàn ạ"),
        ("Seika", "Quyết định rồi không thay đổi đi tập thôi"),
    ],

    # KỊCH BẢN 30: Ngày mưa hát bên cửa sổ
    [
        ("Nijika", "Hôm nay mưa quá không thể về nhà được"),
        ("Kita", "Em thích ngắm mưa ạ mưa đẹp và lãng mạn"),
        ("Ryo", "Mưa buồn tôi thấy nhớ nhà"),
        ("Kikuri", "Mưa là dịp để uống bia trong nhà tuyệt vời"),
        ("Hitori", "Em cũng thích ngắm mưa ạ nó yên bình ạ"),
        ("PA-san", "Mưa lớn có thể gây ngập cẩn thận khi về"),
        ("Seika", "Đừng về gấp ở lại quán cho hết mưa đi"),
        ("Nijika", "Hay chơi thử vài bài acoustic nhé nghe phù hợp với mưa"),
        ("Kita", "Ý hay ạ em hát bài nhẹ nhàng phù hợp với thời tiết ạ"),
        ("Ryo", "Tôi có thể chơi bass chậm tạo không gian"),
        ("Kikuri", "Để tôi lấy cây acoustic ra chơi vài bài"),
        ("Hitori", "Em cũng chơi acoustic ạ âm thanh nó ấm áp ạ"),
        ("Seika", "Tôi pha trà nóng cho mọi người uống cho ấm"),
        ("PA-san", "Âm nhạc acoustic và trà nóng hợp lý đó"),
        ("Nijika", "Bắt đầu bằng bài Guitar to Loneliness nhé"),
        ("Kita", "Em sẽ hát thật nhẹ và cảm xúc ạ"),
        ("Ryo", "Bass nhẹ nhàng hợp với acoustic thôi"),
        ("Kikuri", "Solo guitar acoustic sẽ rất khác biệt"),
        ("Hitori", "Em đánh rhythm mọi người bắt đầu đi ạ"),
        ("Seika", "Nghe hay quá mưa mà có âm nhạc thế này thì tuyệt"),
    ],
]
